#===============================================
# Add new customer
#===============================================
POST http://localhost:30080/customer
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{AZ_API_SUB_KEY}}
Ocp-Apim-Trace: true

{
  "id": "{{$randomInt 1000000 9999999}}",
  "name": "Test Customer",
  "email": "admin@testcustomer.com"
}

###


#===============================================
# Publish CustomerCreated event
#===============================================
POST http://localhost:30080/customercreated
Content-Type: application/json
Ocp-Apim-Subscription-Key: {{AZ_API_SUB_KEY}}
Ocp-Apim-Trace: true

{
  "id": "{{$randomInt 1000000 9999999}}",
  "name": "Test Customer",
  "email": "admin@testcustomer.com"
}