apiVersion: apps/v1
kind: Deployment
metadata:
  name: apim-gateway
  namespace: dapr-apim-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apim-gateway
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: apim-gateway
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "apim-gateway"
        dapr.io/config: "daprconfig"
        dapr.io/log-as-json: "true"
        dapr.io/log-level: "debug"
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: apimgateway
        image: mcr.microsoft.com/azure-api-management/gateway:latest
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /internal-status-0123456789abcdef
            port: http
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        env:
        - name: config.service.auth
          valueFrom:
            secretKeyRef:
              name: eshop-apim-gateway-token
              key: value
        envFrom:
        - configMapRef:
            name: eshop-apim-gateway-env
---
apiVersion: v1
kind: Service
metadata:
  name: apim-gateway
  namespace: dapr-apim-sample
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30080
  - name: https
    port: 443
    targetPort: 8081
    nodePort: 30081
  selector:
    app: apim-gateway